# Generated by Django 4.0.2 on 2022-03-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_input_delete_text_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='data',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
