# Generated by Django 4.0.2 on 2022-04-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='data',
            field=models.JSONField(),
        ),
    ]
