# Generated by Django 4.0.2 on 2022-04-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_input_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='InputModel',
        ),
    ]
